apiVersion: v1
kind: Service
metadata:
  name: mynginx-svc
  labeles:
    app: mynginx
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30002
    protocal: TCP
  selector:
    app: mynginx
      




    
